### ISSUE TITLE
EVAL METRIC PROTOCAL

### ISSUE THREAD

**Issue by turboxin** [swc-17/SparseDrive#10]
It seems that UniAD and VAD used different eval metric protocal as noted by UAD and PARA-Drive paper

https://openaccess.thecvf.com/content/CVPR2024/papers/Weng_PARA-Drive_Parallelized_Architecture_for_Real-time_Autonomous_Driving_CVPR_2024_paper.pdf

https://arxiv.org/html/2406.17680v1

I'm wondering what did you used for comparision?

**Comment by swc-17** [comment]
As described in paper, the L2 distance evaluation is aligned with VAD, and we re-implemented the evaluation protocol for collision rate.

**Comment by zhiyozhao** [comment]
The code shows that, the original VAD uses L2 metric averaged overtime, while sparsedrive use the current timestamps L2 metric:

VAD:
![image](https://github.com/user-attachments/assets/7dc59211-701f-4cf7-a32b-33a6205bdee4)

Sparsedrive:
![image](https://github.com/user-attachments/assets/90aaf405-984d-40e2-a730-5498b6e47ed3)

**Comment by swc-17** [comment]
Please refer to [this issue](https://github.com/hustvl/VAD/issues/33).
