### ISSUE TITLE
关于速度预测逻辑

### ISSUE THREAD

**Issue by martinchen0776** [swc-17/SparseDrive#12]
‘’‘
if self.output_dim > 8:
if not isinstance(time_interval, torch.Tensor):
time_interval = instance_feature.new_tensor(time_interval)
translation = torch.transpose(output[..., VX:], 0, -1)
velocity = torch.transpose(translation / time_interval, 0, -1)
output[..., VX:] = velocity + anchor[..., VX:]
’‘’
您好，在解码速度时通过residual不断相加，并在decoder中refine，这地方的逻辑不太明白？

**Comment by swc-17** [comment]
Refer to [this](https://github.com/linxuewu/Sparse4D/issues/60).
