### ISSUE TITLE
Please release the config for base model SparseDrive-B as described in the paper

### ISSUE THREAD

**Issue by zhiyozhao** [swc-17/SparseDrive#14]
It would be really helpful.

**Comment by swc-17** [comment]
For now, we do not have plan to release the base config and checkpoint. The main difference between small and base config is already described in paper, mainly differ in backbone (r50->[r101](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/nuimages_semseg/cascade_mask_rcnn_r50_fpn_coco-20e_20e_nuim/cascade_mask_rcnn_r50_fpn_coco-20e_20e_nuim_20201009_124951-40963960.pth)), input image shape(x2, and modify data_aug_conf correspondingly), and training hyperparameters(reported in Tab.7 in paper).  You can reproduce base config exactly with these information.

**Comment by swc-17** [comment]
Sorry, it should be [this](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/nuimages_semseg/cascade_mask_rcnn_r101_fpn_1x_nuim/cascade_mask_rcnn_r101_fpn_1x_nuim_20201024_134804-45215b1e.pth).
