### ISSUE TITLE
Questions about collision rate calculation: why collision rate is not 0 even for GT trajectories?

### ISSUE THREAD

**Issue by zhiyozhao** [swc-17/SparseDrive#18]
I have read about the planning metric code. Why are GT trajectories still have non-zero collision rate even when using Polygen collision detection methods?

And one more question, about the implementation details here:
<img width="604" alt="image" src="https://github.com/user-attachments/assets/fbcdb56b-ef7d-4363-a065-6ffbbc76d285">
Why there is an 0.5 here

**Comment by swc-17** [comment]
Sorry for the late response.
1. Maybe the bounding box annotation and ego vehicle localization is not 100% percent accurate. For example, if one large vehicle is close to ego vehicle enough, a small deviation in yaw angle will make the gt trajectory collide.
2. The center of ego vehicle is not at origin of lidar frame, so we follow UniAD to add a 0.5m offset.

**Comment by zhiyozhao** [comment]
Thanks for your kind reply
