### ISSUE TITLE
tracking problem

### ISSUE THREAD

**Issue by owphoo** [swc-17/SparseDrive#19]
你好，我看代码加了一个衰减参数保证Temporal的anchor能够尽可能传到下一帧，但是是怎么保证在下一帧中它能够继续传递，而不是由下一帧的top 300个anchor中产生?
因为非temporal的部分也是正常产生所有的检测，取topk后也是基本上是当帧所有的检测，
temp_gnn是如何保证最后输出的结果是从temporal的600个而不是当前top k的300个anchor产生？
我的理解是通过与temporal anchor做cross attention达到隐式去除？但这一部分并没有做一些监督，是如何做到的？

also in https://github.com/HorizonRobotics/Sparse4D/issues/83

**Comment by swc-17** [comment]
SparseDrive中并没有对跟踪做太多研究。个人想法，当检测性能足够好，传递到下一帧的anchor既有较高的confidence，同时通过anchor projection得到的位置足够准确，能够保证匈牙利匹配时该anchor匹配到同一个id的gt。

**Comment by owphoo** [comment]
> SparseDrive中并没有对跟踪做太多研究。个人想法，当检测性能足够好，传递到下一帧的anchor既有较高的confidence，同时通过anchor projection得到的位置足够准确，能够保证匈牙利匹配时该anchor匹配到同一个id的gt。

但是第一层单帧检测也做了loss，按道理也能得到较准确的检测，相当于两份检测选一份，好像不太能保证选到上一帧的结果？

**Comment by swc-17** [comment]
检测性能足够好的前提下，1层decoder layer的结果不应该比上一帧6层decoder后的结果更准。

**Comment by owphoo** [comment]
> 检测性能足够好的前提下，1层decoder layer的结果不应该比上一帧6层decoder后的结果更准。

理论上是这样，我自己做了一些实验发现上一帧传过来的基本被后面抑制掉了，尽管它的box还挺准，最后输出的基本上是当前帧的结果

**Comment by swc-17** [comment]
Sparse4Dv3的经验是det收敛后再多训一段时间tracking的性能才会好。

**Comment by swc-17** [comment]
可以看下这个[issue](https://github.com/HorizonRobotics/Sparse4D/issues/45)。

**Comment by WuYiYiYi** [comment]
> > 检测性能足够好的前提下，1层decoder layer的结果不应该比上一帧6层decoder后的结果更准。
> 
> 理论上是这样，我自己做了一些实验发现上一帧传过来的基本被后面抑制掉了，尽管它的box还挺准，但是它的confidence过一层temp gnn refine后就变得很低，最后输出的基本上是当前帧的结果

遇到了同样的问题，请问您解决了吗？能否分享下经验

**Comment by Fight-hawk** [comment]
> > 检测性能足够好的前提下，1层decoder layer的结果不应该比上一帧6层decoder后的结果更准。
> 
> 理论上是这样，我自己做了一些实验发现上一帧传过来的基本被后面抑制掉了，尽管它的box还挺准，但是它的confidence过一层temp gnn refine后就变得很低，最后输出的基本上是当前帧的结果

@owphoo 请问后来跟踪的问题解决了吗，我也遇到了同样的问题，第一层还是跟踪到，到了第二层得分变得很低

**Comment by Fight-hawk** [comment]
> Sparse4Dv3的经验是det收敛后再多训一段时间tracking的性能才会好。

@swc-17 感觉问题不在检测，检测的box已经比较精准了，但是confidence突然在第二层开始变得很低
