### ISSUE TITLE
Is clustering suitable for anchor polylines

### ISSUE THREAD

**Issue by sunbin1357** [swc-17/SparseDrive#2]
In sparsedrive, anchor polylines are obtained by K-Means clustering on the training set. However, polylines like pedestrian crossings are sparse. Is it possible that this might result in an inappropriate initial value?

**Comment by swc-17** [comment]
You can visualize the initial predictions (before first decoder layer) in MapTR. The learned initial predictions are lines pointing in the longitudinal direction, which are dominated by divider and road boundary classes in the learning process. Still, after 6 decoder layers, these lines can be refined to the shape of ped crossing. We think that the influence of initial values is not significant.
