### ISSUE TITLE
question about collision_rate

### ISSUE THREAD

**Issue by mikasa-2024** [swc-17/SparseDrive#20]
Hi, I notice that in your log, there are 2 eval results, the collision rate of second one is better, the reason is that u have adjusted the hyper-parameters like 'score_thresh' and ''static_dis_thresh' in rescore module as mentioned?
Because when I finished training the stage2, only getting collision_rate 0.12% without any changes.

**Comment by swc-17** [comment]
Sorry, I forgot the exact hyper-parameters to get the results in log.  You can try to tune these hyper-parameters, which does not need re-training.
