### ISSUE TITLE
Why does it always report errors during training? And there's a situation where grad_norm equals NaN.

### ISSUE THREAD

**Issue by Wangxuecheng666** [swc-17/SparseDrive#21]
Why does it always report errors during training? And there's a situation where grad_norm equals NaN. This is my training log, how do I fix this problem?[Uploading 20240807_094509.log…]()

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 9.7 task/s, elapsed: 617s, ETA:     0s
All Results write to ./work_dirs/sparsedrive_small_stage1/results.pkl
Formating bboxes of img_bbox
Start to convert detection format...
[>>>>>>>>>                                         ] 1098/6019, 51.0 task/s, elapsed: 22s, ETA:    97sTraceback (most recent call last):
  File "./tools/train.py", line 321, in <module>
    main()
  File "./tools/train.py", line 296, in main
    custom_train_model(
  File "/mnt/wxc/E2E_Planning_work/SparseDrive-main/projects/mmdet3d_plugin/apis/train.py", line 29, in custom_train_model
    custom_train_detector(
  File "/mnt/wxc/E2E_Planning_work/SparseDrive-main/projects/mmdet3d_plugin/apis/mmdet_train.py", line 219, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 266, in after_train_iter
    self._do_evaluate(runner)
  File "/mnt/wxc/E2E_Planning_work/SparseDrive-main/projects/mmdet3d_plugin/core/evaluation/eval_hooks.py", line 94, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 367, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/mnt/wxc/E2E_Planning_work/SparseDrive-main/projects/mmdet3d_plugin/datasets/nuscenes_3d_dataset.py", line 843, in evaluate
    result_files, tmp_dir = self.format_results(
  File "/mnt/wxc/E2E_Planning_work/SparseDrive-main/projects/mmdet3d_plugin/datasets/nuscenes_3d_dataset.py", line 632, in format_results
    name: self._format_bbox(
  File "/mnt/wxc/E2E_Planning_work/SparseDrive-main/projects/mmdet3d_plugin/datasets/nuscenes_3d_dataset.py", line 444, in _format_bbox
    boxes = output_to_nusc_box(
  File "/mnt/wxc/E2E_Planning_work/SparseDrive-main/projects/mmdet3d_plugin/datasets/nuscenes_3d_dataset.py", line 1072, in output_to_nusc_box
    box = NuScenesBox(
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/nuscenes/utils/data_classes.py", line 543, in __init__
    assert not np.any(np.isnan(center))
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 725004) of binary: /home/echo/anaconda3/envs/sparsedrive/bin/python3
Traceback (most recent call last):
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/echo/anaconda3/envs/sparsedrive/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-07_13:32:07
  host      : xc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 725004)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Indestructibleee** [comment]
Same problem.Have you solved it?

**Comment by Wangxuecheng666** [comment]
还没有，是不是只能使用多卡训练呀？
---- Replied Message ----
From ***@***.***> Date 08/07/2024 20:20 To ***@***.***> Cc ***@***.***>、State ***@***.***> Subject Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 
Same problem.Have you solved it?

**Comment by swc-17** [comment]
@Wangxuecheng666 是用的单卡训练吗? 需要降低学习率

**Comment by Wangxuecheng666** [comment]
@swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢

**Comment by swc-17** [comment]
@Wangxuecheng666 可以从1/8开始尝试.这个报错看起来不是训练的问题,而是因为训练发散了,中途评测有nan值报错.

**Comment by 1YuChenyao** [comment]
> @swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢

Hello, have you solved this problem?

**Comment by Wangxuecheng666** [comment]
是的，降低学习率能够解决此问题，但性能会下降很多，尤其是跟踪任务。
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年08月14日 17:20 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 
@swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢
Hello, have you solved this problem?

**Comment by 1YuChenyao** [comment]
> 是的，降低学习率能够解决此问题，但性能会下降很多，尤其是跟踪任务。 ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2024年08月14日 17:20 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) @swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢 Hello, have you solved this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

您是怎么降低的呀，我这边3张4090，学习率降低至1e-4，还是会有这个问题
![image](https://github.com/user-attachments/assets/c0970c4f-8fed-4554-9ace-49fa8e6c17a3)

**Comment by Wangxuecheng666** [comment]
我单张4090，降到0.5e-4和1e-4都可以正常训练
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年08月14日 17:45 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 
是的，降低学习率能够解决此问题，但性能会下降很多，尤其是跟踪任务。 ---- 回复的原邮件 ---- 发件人 @.> 日期 2024年08月14日 17:20 收件人 @.> 抄送至 @.>@.> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) @swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢 Hello, have you solved this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>
您是怎么降低的呀，我这边3张4090，学习率降低至1e-4，还是会有这个问题
image.png (view on web)

**Comment by 1YuChenyao** [comment]
> 我单张4090，降到0.5e-4和1e-4都可以正常训练 ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2024年08月14日 17:45 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 是的，降低学习率能够解决此问题，但性能会下降很多，尤其是跟踪任务。 ---- 回复的原邮件 ---- 发件人 @.> 日期 2024年08月14日 17:20 收件人 @.> 抄送至 @.>@.> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) @swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢 Hello, have you solved this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***> 您是怎么降低的呀，我这边3张4090，学习率降低至1e-4，还是会有这个问题 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

您是将初始学习率lr和min_lr_ratio都调小了嘛

**Comment by Wangxuecheng666** [comment]
只调了lr
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年08月14日 18:11 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 
我单张4090，降到0.5e-4和1e-4都可以正常训练 ---- 回复的原邮件 ---- 发件人 @.> 日期 2024年08月14日 17:45 收件人 @.> 抄送至 @.>@.> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 是的，降低学习率能够解决此问题，但性能会下降很多，尤其是跟踪任务。 ---- 回复的原邮件 ---- 发件人 @.> 日期 2024年08月14日 17:20 收件人 @.> 抄送至 @.>@.> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) @swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢 Hello, have you solved this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 您是怎么降低的呀，我这边3张4090，学习率降低至1e-4，还是会有这个问题 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.>
您是将初始学习率lr和min_lr_ratio都调小了嘛

**Comment by 1YuChenyao** [comment]
> 只调了lr ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2024年08月14日 18:11 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 我单张4090，降到0.5e-4和1e-4都可以正常训练 ---- 回复的原邮件 ---- 发件人 @.> 日期 2024年08月14日 17:45 收件人 @.> 抄送至 @.>@.> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) 是的，降低学习率能够解决此问题，但性能会下降很多，尤其是跟踪任务。 ---- 回复的原邮件 ---- 发件人 @.> 日期 2024年08月14日 17:20 收件人 @.> 抄送至 @.>@.> 主题 Re: [swc-17/SparseDrive] Why does it always report errors during training? And there's a situation where grad_norm equals NaN. (Issue #21) @swc-17 是用单卡训练的，需要降低到多少合适呢？另外，模型训练到一半时会中途报错是什么原因呢？谢谢 Hello, have you solved this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 您是怎么降低的呀，我这边3张4090，学习率降低至1e-4，还是会有这个问题 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 您是将初始学习率lr和min_lr_ratio都调小了嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>
感谢~我去试一下

**Comment by Blake-Jiang** [comment]
想请问一下在 4090 上怎么安装 cuda11.6 呀？用 cuda11.8 可以运行吗？
