### ISSUE TITLE
Question about the ResizeCropFlipImage?

### ISSUE THREAD

**Issue by Slonna** [swc-17/SparseDrive#25]
why cam_intrinsic just multiply by the resize factor instead of the augmented matrix commented below?
https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/datasets/pipelines/augment.py#L24-L29

**Comment by swc-17** [comment]
Only resize changes the camera intrinsic.

**Comment by swc-17** [comment]
Rotation and flip affect extrinsic(lidar2cam).

**Comment by swc-17** [comment]
Sorry for the misleading, we double-checked the code, line 27-29 should be the correct transformation. [issue](https://github.com/swc-17/SparseDrive/issues/49).
