### ISSUE TITLE
is there a way to disable FlashAttention acceleration?

### ISSUE THREAD

**Issue by Lu233** [swc-17/SparseDrive#29]
I don't have a powerful GPU.  I got below error, Is there a way to disable usage of FlashAttention? 
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

**Comment by swc-17** [comment]
Replace "MultiheadFlashAttention" in config to "MultiheadAttention" should work, but it will consume more GPU memory, and is not compatible with the released checkpoint.
