### ISSUE TITLE
NaN detected in cls_loss for decoder 0, skipping

### ISSUE THREAD

**Issue by TmacTmac1992** [swc-17/SparseDrive#31]
Hi, I am training SparseDrive with my own dataset.  During stage 1,  the objection detection and map detection can converge。 But in the middle of training, Nan is detected,  is there any idea to avoid this problem?  I am using 8 A100 for stage 1 training. 

NaN detected in cls_loss for decoder 0, skipping.                                                                                                                                                           
NaN detected in cls_loss for decoder 1, skipping.                                                                                                                                                           
NaN detected in cls_loss for decoder 2, skipping.                                                                                                                                                           
NaN detected in cls_loss for decoder 3, skipping.                                                                                                                                                           
NaN detected in cls_loss for decoder 4, skipping.                                                                                                                                                           
NaN detected in cls_loss for decoder 5, skipping.                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                          
  File "tools/train.py", line 321, in <module>                                                                                                                                                              
    main()                                                                                                                                                                                                  
  File "tools/train.py", line 296, in main                                                                                                                                                                  
    custom_train_model(

**Comment by ltc576935585** [comment]
I met the same problem using 4 H20 for stage 1 training.

**Comment by TmacTmac1992** [comment]
Thanks for feedback.   I already fix the problem. My custom dataset has NaN in box' velocity.
