### ISSUE TITLE
测试输出包含nan数据

### ISSUE THREAD

**Issue by 198265** [swc-17/SparseDrive#35]
我下载了nuscenes数据集，和quick_start里提到的预训练参数，然后进行test测试，发现输出的检测框比较乱，并且到170帧数据后检测框数据就开始变成NAN了（最终轨迹输出正常），请问这是什么问题呢，需要我们先训练一版参数再进行测试吗
![D5C7237B-634E-4357-A271-FFEF1DE46C73](https://github.com/user-attachments/assets/650f28a3-d890-43f3-bb91-ea0cfb4d4aaa)

**Comment by swc-17** [comment]
并不需要重新训练, 代码和config有没有改动?直接test不应该出现问题的.

**Comment by 198265** [comment]
config改成了单卡训练，其他并没有改动，现在定位到了是exp()函数使数据溢出，污染了后续的输出，但还是不太清楚为什么检测框会不准
![111](https://github.com/user-attachments/assets/b77b2aea-ad49-43dc-94ca-51dfcb881a42)

**Comment by swc-17** [comment]
根据图片里的信息，load checkpoint应该有些问题。

**Comment by 198265** [comment]
嗷嗷，我设置调试参数的时候把checkpoint路径搞错了，太感谢了ヾ(≧▽≦*)o

**Comment by 198265** [comment]
请问预训练参数是从这个网址下载吗wget https://download.pytorch.org/models/resnet50-19c8e357.pth -O ckpt/resnet50-19c8e357.pth

**Comment by 198265** [comment]
请问预训练参数是从这个网址下载吗https://download.pytorch.org/models/resnet50-19c8e357.pth

**Comment by swc-17** [comment]
是的。
