### ISSUE TITLE
stage2训练使用多线程卡死问题

### ISSUE THREAD

**Issue by LZH-97** [swc-17/SparseDrive#36]
作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；  

出现的问题点：
![6666 png](https://github.com/user-attachments/assets/df81a0ad-5f86-4937-a672-5c1e488e6cfe)

上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；

在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;

想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？

**Comment by swc-17** [comment]
我们在做其他实验时也有遇到多线程evaluate map时卡死的问题，目前不太清楚到底是什么原因。

**Comment by LZH-97** [comment]
好的。了解，感谢回复

**Comment by whmJohn** [comment]
I have also encountered the same problem.

**Comment by JYS997760473** [comment]
> 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> 
> 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzQyMDcsIm5iZiI6MTcyNjQ3MzkwNywicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmU1ZjUyZGRiZGU4ODI0ZDkwM2EyZGU1NzdkODNkOTdhZTA5YzYyZjBkZjI5OTk1MWRhYTM2ZTNkZDJlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1I0Usm96Y-aLpnWzR9NAIjmmlRDrr2NRJ2Mqmpt6VZs)
> 
> 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> 
> 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> 
> 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？

你好，请问在多卡的时候评测map直接让它走else的逻辑就可以正常跑通吗

**Comment by LZH-97** [comment]
> > 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> > 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzQyMDcsIm5iZiI6MTcyNjQ3MzkwNywicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmU1ZjUyZGRiZGU4ODI0ZDkwM2EyZGU1NzdkODNkOTdhZTA5YzYyZjBkZjI5OTk1MWRhYTM2ZTNkZDJlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1I0Usm96Y-aLpnWzR9NAIjmmlRDrr2NRJ2Mqmpt6VZs)
> > 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> > 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> > 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？
> 
> 你好，请问在多卡的时候评测map直接让它走else的逻辑就可以正常跑通吗

是的，可以走通，我把else里面的三行代码 直接替换掉if 里面的一行代码， 是可以跑通的，请问您这边是有新的bug现象吗？

**Comment by JYS997760473** [comment]
> > > 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> > > 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzQyMDcsIm5iZiI6MTcyNjQ3MzkwNywicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmU1ZjUyZGRiZGU4ODI0ZDkwM2EyZGU1NzdkODNkOTdhZTA5YzYyZjBkZjI5OTk1MWRhYTM2ZTNkZDJlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1I0Usm96Y-aLpnWzR9NAIjmmlRDrr2NRJ2Mqmpt6VZs)
> > > 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> > > 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> > > 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？
> > 
> > 
> > 你好，请问在多卡的时候评测map直接让它走else的逻辑就可以正常跑通吗
> 
> 是的，可以走通，我把else里面的三行代码 直接替换掉if 里面的一行代码， 是可以跑通的，请问您这边是有新的bug现象吗？

没有新的bug，我也是在多卡跑训练的时候在评测发现会出现卡死的情况。

**Comment by ASONG0506** [comment]
> > > > 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> > > > 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzQyMDcsIm5iZiI6MTcyNjQ3MzkwNywicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmU1ZjUyZGRiZGU4ODI0ZDkwM2EyZGU1NzdkODNkOTdhZTA5YzYyZjBkZjI5OTk1MWRhYTM2ZTNkZDJlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1I0Usm96Y-aLpnWzR9NAIjmmlRDrr2NRJ2Mqmpt6VZs)
> > > > 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> > > > 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> > > > 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？
> > > 
> > > 
> > > 你好，请问在多卡的时候评测map直接让它走else的逻辑就可以正常跑通吗
> > 
> > 
> > 是的，可以走通，我把else里面的三行代码 直接替换掉if 里面的一行代码， 是可以跑通的，请问您这边是有新的bug现象吗？
> 
> 没有新的bug，我也是在多卡跑训练的时候在评测发现会出现卡死的情况。

遇到类似的情况，stage1的时候，训练5w多步做评测直接卡死了，显存没清，程序挂了

**Comment by ASONG0506** [comment]
> 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> 
> 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIxNTQsIm5iZiI6MTcyNjczMTg1NCwicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDg3MDE1Y2E5ZTg3MjliNzg4ZDNlMGFhNjAzZTA2OWFlYzU2ZmI4ZmZlN2M4OGI0NzAyOGY4ZTllMDE1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wsj8rRhuzhkEoN2E0vQA72140hs4p9Z04uNchk7RXd4)
> 
> 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> 
> 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> 
> 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？

hello，能提供一下你卡住的log吗，想参考一下，谢谢

**Comment by LZH-97** [comment]
> > 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> > 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIxNTQsIm5iZiI6MTcyNjczMTg1NCwicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDg3MDE1Y2E5ZTg3MjliNzg4ZDNlMGFhNjAzZTA2OWFlYzU2ZmI4ZmZlN2M4OGI0NzAyOGY4ZTllMDE1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wsj8rRhuzhkEoN2E0vQA72140hs4p9Z04uNchk7RXd4)
> > 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> > 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> > 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？
> 
> hello，能提供一下你卡住的log吗，想参考一下，谢谢

![image](https://github.com/user-attachments/assets/1b0dc2df-a752-43bb-91d0-9fa780baf125)
大概是这样的，一直evaluating 3 categories.......但是0/3一直是0/3，一直不动，而且对应的python train.py进程似乎也被杀停了，但是命令行是一直卡在这里不动，也不报error

**Comment by ASONG0506** [comment]
> > > 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> > > 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIxNTQsIm5iZiI6MTcyNjczMTg1NCwicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDg3MDE1Y2E5ZTg3MjliNzg4ZDNlMGFhNjAzZTA2OWFlYzU2ZmI4ZmZlN2M4OGI0NzAyOGY4ZTllMDE1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wsj8rRhuzhkEoN2E0vQA72140hs4p9Z04uNchk7RXd4)
> > > 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> > > 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> > > 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？
> > 
> > 
> > hello，能提供一下你卡住的log吗，想参考一下，谢谢
> 
> ![image](https://private-user-images.githubusercontent.com/73765725/368900094-1b0dc2df-a752-43bb-91d0-9fa780baf125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzQwMDQsIm5iZiI6MTcyNjczMzcwNCwicGF0aCI6Ii83Mzc2NTcyNS8zNjg5MDAwOTQtMWIwZGMyZGYtYTc1Mi00M2JiLTkxZDAtOWZhNzgwYmFmMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA4MTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NGM0Yjg2M2QzZmJjMDAxMTJlMThiMDhhZjI4NzNmZTNkZGM2YWY0Y2JlODRjMmIwY2M3ZjVmNWUxNzM2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tSuWC_wgdsrVrqiVhSDbMs_G27n3qgmOMWdPwZeCcDI) 大概是这样的，一直evaluating 3 categories.......但是0/3一直是0/3，一直不动，而且对应的python train.py进程似乎也被杀停了，但是命令行是一直卡在这里不动，也不报error

我这边也这样，看起来是正常的，这块做map的评测，在我的服务器，有的时候这部分评测要跑40分钟到1个小时。看样子你多等一会就好了。

**Comment by LZH-97** [comment]
> > > > 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> > > > 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIxNTQsIm5iZiI6MTcyNjczMTg1NCwicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDg3MDE1Y2E5ZTg3MjliNzg4ZDNlMGFhNjAzZTA2OWFlYzU2ZmI4ZmZlN2M4OGI0NzAyOGY4ZTllMDE1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wsj8rRhuzhkEoN2E0vQA72140hs4p9Z04uNchk7RXd4)
> > > > 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> > > > 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> > > > 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？
> > > 
> > > 
> > > hello，能提供一下你卡住的log吗，想参考一下，谢谢
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/73765725/368900094-1b0dc2df-a752-43bb-91d0-9fa780baf125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzQwMDQsIm5iZiI6MTcyNjczMzcwNCwicGF0aCI6Ii83Mzc2NTcyNS8zNjg5MDAwOTQtMWIwZGMyZGYtYTc1Mi00M2JiLTkxZDAtOWZhNzgwYmFmMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA4MTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NGM0Yjg2M2QzZmJjMDAxMTJlMThiMDhhZjI4NzNmZTNkZGM2YWY0Y2JlODRjMmIwY2M3ZjVmNWUxNzM2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tSuWC_wgdsrVrqiVhSDbMs_G27n3qgmOMWdPwZeCcDI) 大概是这样的，一直evaluating 3 categories.......但是0/3一直是0/3，一直不动，而且对应的python train.py进程似乎也被杀停了，但是命令行是一直卡在这里不动，也不报error
> 
> 我这边也这样，我觉得是正常的，这块做map的评测，在我的服务器，有的时候这部分评测要跑40分钟到1个小时。看样子你多等一会就好了。

我跑过好几次，跑到这里都是等了一晚上都没出来，至少每次都等5个小时以上，后面再跑的时候我监视了一下nvidia-smi，跑到这里utils已经变成0了，在进程监视栏中我启动的python train.py这个进程也挂掉了，感觉应该是没戏了，就停掉了。您这边是完全可以跑通的是吧，能问一下您这边的配置，是不是用了多个GPU，是我这边一张A100的显存不够吗？

**Comment by ASONG0506** [comment]
> > > > > 作者您好，想咨询个问题，就是我在使用A100单卡进行stage2训练时发现，当我的config中的eval_mode保持原有设置不变时，每次都会在多线程的evaluate时卡死，只有把eval_mode中的“with_map”设置为False，才能够多线程运行；而且在stage1 训练的时候也是同样的问题，当eval_mode中的“with_map”打开时，也出现了多线程evaluate卡死的问题；
> > > > > 出现的问题点： ![6666 png](https://private-user-images.githubusercontent.com/73765725/364385147-df81a0ad-5f86-4937-a672-5c1e488e6cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIxNTQsIm5iZiI6MTcyNjczMTg1NCwicGF0aCI6Ii83Mzc2NTcyNS8zNjQzODUxNDctZGY4MWEwYWQtNWY4Ni00OTM3LWE2NzItNWMxZTQ4OGU2Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDg3MDE1Y2E5ZTg3MjliNzg4ZDNlMGFhNjAzZTA2OWFlYzU2ZmI4ZmZlN2M4OGI0NzAyOGY4ZTllMDE1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wsj8rRhuzhkEoN2E0vQA72140hs4p9Z04uNchk7RXd4)
> > > > > 上面的图片是卡死报错的具体位置点，然后我设置的n_works=2, len_samples是nusence数据集中的6019个；
> > > > > 在我的训练中，GPU是单卡A100， CPU是Intel(R) Xeon(R) Platinum 8350C， batchsize = 8;
> > > > > 想咨询一下作者，在evaluate多线程加速时，还需要改动其他什么参数吗？
> > > > 
> > > > 
> > > > hello，能提供一下你卡住的log吗，想参考一下，谢谢
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/73765725/368900094-1b0dc2df-a752-43bb-91d0-9fa780baf125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzQwMDQsIm5iZiI6MTcyNjczMzcwNCwicGF0aCI6Ii83Mzc2NTcyNS8zNjg5MDAwOTQtMWIwZGMyZGYtYTc1Mi00M2JiLTkxZDAtOWZhNzgwYmFmMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA4MTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NGM0Yjg2M2QzZmJjMDAxMTJlMThiMDhhZjI4NzNmZTNkZGM2YWY0Y2JlODRjMmIwY2M3ZjVmNWUxNzM2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tSuWC_wgdsrVrqiVhSDbMs_G27n3qgmOMWdPwZeCcDI) 大概是这样的，一直evaluating 3 categories.......但是0/3一直是0/3，一直不动，而且对应的python train.py进程似乎也被杀停了，但是命令行是一直卡在这里不动，也不报error
> > 
> > 
> > 我这边也这样，我觉得是正常的，这块做map的评测，在我的服务器，有的时候这部分评测要跑40分钟到1个小时。看样子你多等一会就好了。
> 
> 我跑过好几次，跑到这里都是等了一晚上都没出来，至少每次都等5个小时以上，后面再跑的时候我监视了一下nvidia-smi，跑到这里utils已经变成0了，在进程监视栏中我启动的python train.py这个进程也挂掉了，感觉应该是没戏了，就停掉了。您这边是完全可以跑通的是吧，能问一下您这边的配置，是不是用了多个GPU，是我这边一张A100的显存不够吗？

我是4*3090的服务器。24G显存
确实配置也不太顶，跑起来发现了好多次卡到NCCL 报错timeout，显存占用，但是程序挂了的情况。
但是这个问题和GPU应该是无关的，问题出在车道线评测这里，是cpu上的操作。
我把train.sh中的
`        dist.init_process_group(
            backend="nccl",
            init_method=args.dist_url,
            world_size=mpi_world_size,
            rank=mpi_local_rank,
            timeout=timedelta(seconds=3600),
        )`
这里的timeout=timedelta(seconds=3600）改成36000，扩大到10hours，目前看来没啥问题了。你可以试试把你机器上的这个数值加的更大，防止cpu上操作时间太久最后崩掉的情况。

**Comment by LZH-97** [comment]
> 起来发现了好多次卡到NCCL 报错time

 感谢指导，我有空试试，感谢！！！
