### ISSUE TITLE
About FlashAttention

### ISSUE THREAD

**Issue by Zbozhou** [swc-17/SparseDrive#37]
Thanks for your excellent work，I am wondering why FlashAttention is not used in the **temp_graph_model** of **motion_plan_head**
![image](https://github.com/user-attachments/assets/2c69459e-6fdf-46d9-8def-29059753e475)

**Comment by swc-17** [comment]
We use key_padding_mask in temporal attention, but FlashAttention copied from StreamMapNet does not support using mask.

**Comment by Zbozhou** [comment]
Thanks for your reply. I also noticed that **decouple_attn** is used in the detection head and motion_plan head, but not in the map head. Why is that?

**Comment by swc-17** [comment]
We found using decouple_attn for map does not improve performance.

**Comment by Zbozhou** [comment]
Thanks for your reply.
