### ISSUE TITLE
为什么在SparseDrive里把Sparse4D提出的denoise关掉了呢

### ISSUE THREAD

**Issue by JYS997760473** [swc-17/SparseDrive#39]
![image](https://github.com/user-attachments/assets/11753cab-550a-477a-8d81-f85a85f60d70)
感谢提出这么有意义的工作，有个问题想请教一下，为什么在SparseDrive要把Sparse4D提出的denoise 关掉呢

**Comment by swc-17** [comment]
1.这篇工作并不过分追求优异的感知性能
2.加上dn会有更多显存占用
如果需要的话可以自行打开dn。

**Comment by JYS997760473** [comment]
> 1.这篇工作并不过分追求优异的感知性能 2.加上dn会有更多显存占用 如果需要的话可以自行打开dn。

谢谢！
