### ISSUE TITLE
The augmentation is not applied for motion & planning

### ISSUE THREAD

**Issue by zhangyp15** [swc-17/SparseDrive#4]
Hi, thanks for the great work and contributions. 

When checking the data pipelines, I found that the motion & planning labels (though they are in LiDAR coordinates) are not transformed according to the augmentations. I wonder whether I missed some details or this is intended?

**Comment by swc-17** [comment]
Data augmentations are only performed in image space rather than BEV space (rot3d_range is set to [0, 0]), so there is no need to transform motion & planning labels.

**Comment by zhangyp15** [comment]
Thanks for your reply. I also found the baseline Sparse4D (for detection & tracking) performs the BEV augmentation with "rot3d_range": [-0.3925, 0.3925]. 

Why is it disabled for the end-to-end SparseDrive?

**Comment by swc-17** [comment]
We found that data augmentation in BEV space seems to have negative effect for online mapping task.
