### ISSUE TITLE
训练过程中loss变成nan了

### ISSUE THREAD

**Issue by suayu** [swc-17/SparseDrive#41]
![nan](https://github.com/user-attachments/assets/c9fc4aa9-0e8f-42ff-bffe-d709c689a08d)
用的nuScenes数据集，一张RTX3070上训练。请问可能发生了什么问题？

**Comment by swc-17** [comment]
单卡训练需要降低学习率。

**Comment by suayu** [comment]
谢谢。把两阶段学习率降了1/2和2/3之后不再出现loss和梯度变nan的问题。

**Comment by suayu** [comment]
谢谢。把两阶段学习率降了1/2和2/3之后不再出现loss和梯度变nan的问题。
