### ISSUE TITLE
使用A100 8张卡训练第一阶段loss基本都为0

### ISSUE THREAD

**Issue by JYS997760473** [swc-17/SparseDrive#42]
我在使用A100 8张卡训练的时候发现loss从一开始就基本为0，但是如果是4张A10上训练loss就比较正常，这是为什么呢？模型方面以及配置都没有动
![image](https://github.com/user-attachments/assets/333f5c7a-d43c-4de3-ae87-c0f7c8d3e8ca)
![image](https://github.com/user-attachments/assets/2d9be4e8-3de3-40e0-9e50-a93c4c5db762)

**Comment by SophieZhou** [comment]
I met the same problem. have you solved it?

**Comment by JYS997760473** [comment]
> I met the same problem. have you solved it?

算子的问题，在A100上重新编译算子就行

**Comment by SophieZhou** [comment]
> > I met the same problem. have you solved it?
> 
> 算子的问题，在A100上重新编译算子就行

谢谢，是ops下重新编译就好了吗？我是python setup.py clean，然后再编译后，evaluation正常，但是train的还是不正常，focal loss是0.
