### ISSUE TITLE
带 --show 运行时BUG，TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by liushuquan2022** [swc-17/SparseDrive#45]
感谢作者分享！一个显示输出时的BUG，请方便时回复，谢谢！

1）运行：
python tools/test.py projects/configs/sparsedrive_small_stage1.py ckpt/sparsedrive_stage1.pth --show --show-dir  show_dirs/sparsedrive_small_stage1/results.pkl --show_only 

2）报错信息：
文件：Lib/site-packages/mmdet/apis/test.py：
            if batch_size == 1 and isinstance(data['img'][0], torch.Tensor):
信息：
TypeError: 'DataContainer' object is not subscriptable

3）部署环境按作者要求搭建。

**Comment by swc-17** [comment]
并不支持test的时候show，应该在test完通过scripts/visualize.sh进行可视化。

**Comment by liushuquan2022** [comment]
感谢回复。
