### ISSUE TITLE
在自己的数据集上A10，A100， A800的表现完全不一样

### ISSUE THREAD

**Issue by JYS997760473** [swc-17/SparseDrive#47]
你好，我们发现在使用自己的数据集时候训练，同样的模型配置，同样的8卡，在A10上训练loss能正常下降，但是在A100，A800机器上训练loss就完全不下降，一直震荡，请问您这边有遇到过这种情况吗？推测这是什么原因呢？

**Comment by swc-17** [comment]
op是在哪台机器上编译的?可以尝试一下在目标机器重新编译一下.

**Comment by JYS997760473** [comment]
> op是在哪台机器上编译的?可以尝试一下在目标机器重新编译一下.

感谢回复，op我还在每次训练前都特意编译一次然后再跑训练，请问每次都是需要删除上次训练编译的.so等然后再编译吗？或者说还有没有其他可能的原因呢

**Comment by JYS997760473** [comment]
> op是在哪台机器上编译的?可以尝试一下在目标机器重新编译一下.

我把编译好的东西删掉再编译正常了 感谢感谢

**Comment by PeterJaq** [comment]
> > op是在哪台机器上编译的?可以尝试一下在目标机器重新编译一下.
> 
> 感谢回复，op我还在每次训练前都特意编译一次然后再跑训练，请问每次都是需要删除上次训练编译的.so等然后再编译吗？或者说还有没有其他可能的原因呢

我也发生过一样的问题，mmcv都得重新编译安装，focal loss不重新编译 focal loss这些压根不正常。。。(3080训练/A800训练)
