### ISSUE TITLE
Variation of input sampling frequency 

### ISSUE THREAD

**Issue by julien-seitz** [swc-17/SparseDrive#48]
Hello,
thanks much for sharing your repository.
I successfully got training and inference running on my side and am impressed about the result.

One question:
I assume that the dataset is currently trained based on the frequency of the NuScenes samples of 2Hz (500ms).
Do you know if it is possible to apply inference on higher frequent input images (e.g. 10Hz) and does this require changing some parameters? And do you assume this requires a re-training on higher frequent dataset?

**Comment by swc-17** [comment]
Hi, I think it does require re-training, as our motion planner has a time window of 4 frames (2s), which may not directly fit to a high frequency dataset.

**Comment by julien-seitz** [comment]
Thanks much,
I tried to deactivate the motion_planning and the mapping module and just looked at the detector.
As I currently do not have a dataset with higher frequency, I tried to apply inference on higher sampled data without without ground truth data.
With 2Hz the detection works quite fine. With 10Hz however, the quality seems to be slightly worse: Some objects are not detected and some objects are not correctly tracked so that I see some ID switches.

While debugging, I figured out that the time interval in:
https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/models/detection3d/detection3d_blocks.py#L144
time_interval needs to stay at 0.5s even if the delta between input frames gets smaller because of the high frequency.
This seems to be because the network learns to predict a translation from one frame to the next frame and this translation is then transformed into a velocity. This the time-delta of the dataset and not the inference is relevant here.
(that helped already, but the quality is still worse than with 2Hz)

Regarding that, do you know if there is a reason why the network is predicting some translations instead of directly predicting the velocity?
And a second question related to that part: Do you know why the velocity is not part of the "refine_state"? The other attributes, X, Y, Z, L, W, H and optionally COS_YAW, SIN_YAW are refined by adding the estimated deltas, whereas for the translation/velocity no delta values but instead absolute estimates are used and they are overwriting the estimate from the previous refinement step. Do you know if there is a reason?

And last: do have in mind if there are further locations in the detector that might need to be adjusted to use the detector with higher frequency?

Thanks very much
(I will also try to investigate this further on my own)

**Comment by swc-17** [comment]
Sorry for the late response. Have you tried to modify time_interval using 10Hz data?

**Comment by julien-seitz** [comment]
Yes I tried modifying all occurences of time_interval to 0.1s as well as changing all except the one in this line
https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/models/detection3d/detection3d_blocks.py#L144
Both variants result in significantly worse results compared to 2Hz.
But keeping time_interval in
https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/models/detection3d/detection3d_blocks.py#L144
at 0.5 leads to better results (still significantly worse than with 2Hz)

**Comment by swc-17** [comment]
Maybe the domain gap between training and inference matters here, I suggest you retrain the model at 10Hz. There is one hyper-parameter which may be important here, the confidence_decay should be tuned if the frequency is changed.

**Comment by julien-seitz** [comment]
Thanks. Yes I will have a look at that parameter.
Currently we are trying to prepare a dataset with 10Hz.
I also assume that there might be a domain gap.
