### ISSUE TITLE
det_head config

### ISSUE THREAD

**Issue by bowang9711** [swc-17/SparseDrive#50]
Could you please clarify the rationale behind the inclusion of a [2:] slicing operation in the operation_order of det_head within the configuration, while it is absent in the map component?
![1](https://github.com/user-attachments/assets/1901f616-7fd8-49a9-966f-9a71ebdbedee)

**Comment by swc-17** [comment]
Sparse4Dv2 initializes instance features as 0 and removes first two layers in single_frame_decoder, which improves detection performance. However,  in our previous experiment, it's not helpful to online mapping, so we keep all layers for mapping.
