### ISSUE TITLE
关于使用单卡GPU训练

### ISSUE THREAD

**Issue by guoyage** [swc-17/SparseDrive#53]
为了节省训练时间，我直接加载sparsedrive_stage1.pth权重，并直接开始stage 2阶段的训练。由于我只有单张3090卡，因此在sparsedrive_small_stage2.py配置文件中，我手动将下面若干参数进行了调整，分别是：total_batch_size = 6，num_gpus = 1，此外学习率初始值为lr=3e-4，我将其调整为1e-4，但是从训练的loss来看，似乎损失下降的不太正常，请问还有参数需要调整吗？？或者是每次开始新的训练过程，首先要重新编译mmcv和.so文件？？？期待您的答复。
![image](https://github.com/user-attachments/assets/1b893124-9add-4617-936b-35f662d5b925)

**Comment by swc-17** [comment]
loss有震荡也正常，可以先多训练一会，如果loss不降低可以再降低lr试试。

**Comment by guoyage** [comment]
> loss有震荡也正常，可以先多训练一会，如果loss不降低可以再降低lr试试。

你好，这是我训练的部分结果，大约6个epoch，loss震荡的还是比较厉害的，您给出的loss相对下降较为平缓，这可能是什么原因导致的？
![image](https://github.com/user-attachments/assets/94516984-afa9-4f97-ac2e-a733badc1f54)

**Comment by swc-17** [comment]
有没有尝试再降低lr？

**Comment by ChosenOne-xx** [comment]
您好，我也是单卡训练，我是16G的4080，但在保存checkpoint时会被中断（调小了batch_size，显存应该是够的），所以我想请问一下您有成功跑完模型吗？单GPU是否真的可以进行训练？如果可以的话我想请教一下您是怎么做的。期待您的回复，万分感谢！
