### ISSUE TITLE
Images Preprocess

### ISSUE THREAD

**Issue by waynechu1109** [swc-17/SparseDrive#55]
![predeal_with](https://github.com/user-attachments/assets/c9025ab6-d42d-4cef-b977-699c9c89241a)
![0000](https://github.com/user-attachments/assets/d7904620-d365-49df-9632-0605b75f6677)

Hello!

We are doing some experiments using SparseDrive. When we printed the output images, we discovered that the data loader preprocessed the input images before it actually loaded into the model. (As shown in the top image, the original input image is shown in the bottom.) 

Could you please reveal that what kind of preprocess the dataloader do on the image?

Thanks for your kind help!

**Comment by swc-17** [comment]
Please refer to train_pipeline in config file.

**Comment by waynechu1109** [comment]
Hello, 

Thanks for your quick response. Based on my understanding, "train_pipeline in config file" contains the information for model training. However, the preprocess process of the images before sending them into the model seems not include in the train_pipeline.

**Comment by swc-17** [comment]
Hi, the images are preprocessed by test_pipeline if you are referring to the inference process, the preprocess includes LoadMultiViewImageFromFiles, ResizeCropFlipImage and NormalizeMultiviewImage.

**Comment by waynechu1109** [comment]
Hello, 

Thanks for your help, now we have successfully preprocessed our images. However, another problem occurred, after we directly feed the preprocessed images to the model, the model cannot recognize the objects properly. Is there anything else we need to feed into the model for better recognition? Thank you!

The result in the top is generated by original method while the result in the bottom is generated by our experiment. You can see that we directly put the preprocessed images into the model and only 4 cars are recognized. 

![good_with_original_images](https://github.com/user-attachments/assets/eaef68f2-95e3-45c6-af15-e8002ba67567)
![correct_color_crop_notGood_2](https://github.com/user-attachments/assets/07854550-b944-475d-af2d-a13e2af83f63)

**Comment by swc-17** [comment]
Did you compare your preprocessed image with the image output by dataloader? Make sure they are same.

**Comment by waynechu1109** [comment]
Thanks for your response! We have successfully found the solution.
