### ISSUE TITLE
FileNotFoundError: ckpt/sparsedrive_stage1.pth can not be found.

### ISSUE THREAD

**Issue by zhangzscn** [swc-17/SparseDrive#56]
想请教一下，这个sparsedrive_stage1.pth文件是一阶段训练完，自动保存到这个路径下的嘛？我一阶段训练完了，但是执行第二阶段训练时，提示缺少这个文件。

**Comment by swc-17** [comment]
你可以下载我们给出的ckpt，或者将你训练得到的stage1的ckpt移动到ckpt/文件夹，或者更改config file里的load_from变量。
