### ISSUE TITLE
关于预测周边车辆轨迹与自车规划轨迹的时间步长问题

### ISSUE THREAD

**Issue by guoyage** [swc-17/SparseDrive#57]
您好，通过对代码的研读，我发现文章对周边车辆的轨迹预测采用了12个时间步长，但是对于自车的轨迹规划采用了6个时间步长，请问为何两个时间步长不设置为相同值？

**Comment by swc-17** [comment]
我们是follow了uniad的setting以方便进行对比。

**Comment by wowowolala** [comment]
請問 可以修改自車軌跡預測時間及周邊車輛預測軌跡 (加長時間到 10 秒 )嗎?

**Comment by swc-17** [comment]
可以自行修改。
