### ISSUE TITLE
在mini数据集上使用sh scripts/kmeans.sh 问题

### ISSUE THREAD

**Issue by shuiyihang** [swc-17/SparseDrive#58]
在执行kmeans_plan.py时出现错误ValueError: need at least one array to concatenate

![image](https://github.com/user-attachments/assets/ac7f2e16-d879-4993-a64d-89a810dee8c7)

我尝试在增加判断trajs为空则continue，但是这样做似乎会导致训练的时候尺寸不对。请问作者有在mini上测试过遇到相同问题吗

**Comment by shuiyihang** [comment]
这是我的数据集目录
![image](https://github.com/user-attachments/assets/046c9b69-176e-4d2a-8fcd-851b23bcfff4)

**Comment by guoyage** [comment]
> 这是我的数据集目录 ![image](https://private-user-images.githubusercontent.com/43931349/375917455-046c9b69-176e-4d2a-8fcd-851b23bcfff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTYwODUsIm5iZiI6MTcyODcxNTc4NSwicGF0aCI6Ii80MzkzMTM0OS8zNzU5MTc0NTUtMDQ2YzliNjktMTc2ZS00ZDJhLThmY2QtODUxYjIzYmNmZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2NDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MWRhNDUxNzU1MmE0ZGJhZGFlN2IzM2U5N2QyODBjZjUwZTcxODliZjlkYzU4ZDM5YWIyMjZkNDZiNjVmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uvPLZLDBrTuzccHguVukJ4I7H8dDXrGFrUYJa3E4y1E)

不能用mini数据集，要用full数据集

**Comment by shuiyihang** [comment]
> > 这是我的数据集目录 ![image](https://private-user-images.githubusercontent.com/43931349/375917455-046c9b69-176e-4d2a-8fcd-851b23bcfff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTYwODUsIm5iZiI6MTcyODcxNTc4NSwicGF0aCI6Ii80MzkzMTM0OS8zNzU5MTc0NTUtMDQ2YzliNjktMTc2ZS00ZDJhLThmY2QtODUxYjIzYmNmZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2NDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MWRhNDUxNzU1MmE0ZGJhZGFlN2IzM2U5N2QyODBjZjUwZTcxODliZjlkYzU4ZDM5YWIyMjZkNDZiNjVmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uvPLZLDBrTuzccHguVukJ4I7H8dDXrGFrUYJa3E4y1E)
> 
> 不能用mini数据集，要用full数据集

好的bro，我下载完整的测试

**Comment by Lewis-Lu** [comment]
You don't have to necessarily generate plan_6 using full dataest. It is raised by the the `cmd` distribution in the mini dataset, where len(navi_trajs[0]) = 0

the len(navi_trajs) is [0, 26, 249] which indicates this situation.

To fix this Error, naively modify (add two lines) the code will serve the purpose.

clusters = []
for trajs in navi_trajs:
    **if(0 == len(trajs)):
        continue**

Best,
Lewis

**Comment by Lewis-Lu** [comment]
> You don't have to necessarily generate plan_6 using full dataest. It is raised by the the `cmd` distribution in the mini dataset, where len(navi_trajs[0]) = 0
> 
> the len(navi_trajs) is [0, 26, 249] which indicates this situation.
> 
> To fix this Error, naively modify (add two lines) the code will serve the purpose.
> 
> clusters = [] for trajs in navi_trajs: **if(0 == len(trajs)): continue**
> 
> Best, Lewis

Well, this causes the new issue during test.py process as shown below: 

size mismatch for head.motion_plan_head.plan_anchor: copying a param with shape torch.Size([3, 6, 6, 2]) from checkpoint, the shape in current model is torch.Size([2, 6, 6, 2]).

Maybe could just duplicate the cmd[0] and cmd[2], but just in two opposite directions. I will update here to see if such anchor affects the accuracy.

**Comment by andyxiao2022** [comment]
@Lewis-Lu do you mean add  cmd[0] = cmd[2] after the line   cmd = info['gt_ego_fut_cmd'].astype(np.int32)? 
"

**Comment by Lewis-Lu** [comment]
> [@Lewis-Lu](https://github.com/Lewis-Lu) do you mean add cmd[0] = cmd[2] after the line cmd = info['gt_ego_fut_cmd'].astype(np.int32)? "

@andyxiao2022 

```
clusters = []
is_zeros = []
for i in range(len(navi_trajs)):
    trajs = navi_trajs[i]
    if(0 == len(trajs)):
        is_zeros.append(i)
        continue
    trajs = np.concatenate(trajs, axis=0).reshape(-1, 12)
    cluster = KMeans(n_clusters=K).fit(trajs).cluster_centers_
    cluster = cluster.reshape(-1, 6, 2)
    clusters.append(cluster)
    for j in range(K):
        plt.scatter(cluster[j, :, 0], cluster[j, :,1])

if len(is_zeros) != 0:
    clusters.insert(is_zeros[0], -clusters[0])
```

pretty ugly workaround, you can have your own version. `clusters.insert(is_zeros[0], -clusters[0])` this line do the work.
