### ISSUE TITLE
Loss function問題

### ISSUE THREAD

**Issue by wowowolala** [swc-17/SparseDrive#59]
你好，

![image](https://github.com/user-attachments/assets/9d700167-9b45-4a05-bba7-2e6511d439af)

請問上方論文中提到的 ground truth trajectory 是根據甚麼得到的? 
nuscenes 中好像沒有關於 trajectory 的資料。

**Comment by swc-17** [comment]
nuscenes没有提供planning的轨迹，但可以通过未来的位姿信息转化得到，具体可以参考tools/data_converter/nuscenes_converter.py。
