### ISSUE TITLE
使用sh scripts/test.sh，出现[                                                  ] 0/3, elapsed: 0s, ETA:./tools/dist_test.sh: 第 13 行： 114146 已杀死               PYTHONPATH="$(dirname $0)/..":$PYTHONPATH python3 $(dirname "$0")/test.py $CONFIG $CHECKPOINT ${@:4}

### ISSUE THREAD

**Issue by shuiyihang** [swc-17/SparseDrive#61]
正常情况下我的机子内存如图
![image](https://github.com/user-attachments/assets/9f9f43f5-b365-4329-91fc-b7e5a7bd60c3)

运行test.sh，总是在这里被系统杀死，我已经尝试将交换内存扩充到由原来的2G扩充到16G仍然出现相同问题。(尝试过三次，包括扩充交换内存后一次)
![image](https://github.com/user-attachments/assets/5ab6a3ed-4b53-41a9-946d-4a5b460eb52f)

当被系统杀死之后，脚本运行的程序仍然占用很大的内存
![image](https://github.com/user-attachments/assets/d4c8aea8-424f-4cea-9694-8dda971a260d)

![image](https://github.com/user-attachments/assets/5df43463-edb1-45fa-a473-ccd26355c49a)

请问作者测试对环境的内存要求最低多少，或者我该做一些什么尝试，感谢感谢！！

**Comment by swc-17** [comment]
看到你是在eval map时报错，可以尝试把多线程eval改为单线程，不过会变的慢一些。projects/mmdet3d_plugin/datasets/evaluation/map/vector_eval.py把N_WORKERS 设置为0试一下。

**Comment by shuiyihang** [comment]
> 看到你是在eval map时报错，可以尝试把多线程eval改为单线程，不过会变的慢一些。projects/mmdet3d_plugin/datasets/evaluation/map/vector_eval.py把N_WORKERS 设置为0试一下。

谢谢，将N_WORKERS 改为0确实有效，终于成功跑了测试，但是再eval阶段花费的时间有一个多小时，后续将N_WORKERS 缩半为8试一下
