### ISSUE TITLE
有关双卡GPU训练报错的问题。

### ISSUE THREAD

**Issue by guoyage** [swc-17/SparseDrive#63]
我直接开始stage2阶段的训练，使用了2块3090GPU，但是在训练时遇到如下错误：RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 157 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

定位原因是：Parameter at index 157 with name img_backbone.layer4.2.bn3.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.

这可能是什么原因导致的？该如何解决？期待您的回复

**Comment by swc-17** [comment]
您好，问题是否解决？之前似乎遇到过类似报错，但忘了具体原因了。

**Comment by guoyage** [comment]
> 您好，问题是否解决？之前似乎遇到过类似报错，但忘了具体原因了。

您好，已经解决了。谢谢

**Comment by ASONG0506** [comment]
> > 您好，问题是否解决？之前似乎遇到过类似报错，但忘了具体原因了。
> 
> 您好，已经解决了。谢谢

你好想请问一下你是怎么解决的，谢谢
