### ISSUE TITLE
推論時間的FPS定義問題？

### ISSUE THREAD

**Issue by waynechu1109** [swc-17/SparseDrive#65]
作者您好，根據論文的敘述 inference 時使用一張RTX 4090，執行速度為FPS 9.0，
因為環周影像一次是6張相片同時由Dataloader輸入，
想請問這裡只的FPS 9.0，是把6張環周相片視為一張影像？
還是輸入的6張環周影像算為6張影像？

![image](https://github.com/user-attachments/assets/129fd494-ff25-4ab2-ab74-62d5b53565dd)

我目前使用RTX 4080執行一次6張相片視為一個影像的效率約為1.5秒，
大約為FPS 0.667，因此想確認是否符合論文描述，謝謝。

**Comment by swc-17** [comment]
是环视六张图像一起输入，可以使用tools/benchmark.py测试FPS。

**Comment by swc-17** [comment]
I think some layers like deformable aggregation better works at fp32, other layers can be converted to fp16.

**Comment by Anthony1011** [comment]
Thanks for your help and suggestions. I have figured it out, and now I am using the RTX 4080 for inference. Its performance is approximately 3-4 FPS, which is lower than my expectation of 6.3 FPS (calculated as fps 9 * 0.7).
Have you released an FP16 quantization version?
I sincerely appreciate your efforts.

**Comment by swc-17** [comment]
The model is trained with fp32 weights, you can run model with fp16 using torch.autocast.
