### ISSUE TITLE
有关模型验证阶段，内存out of memory问题

### ISSUE THREAD

**Issue by guoyage** [swc-17/SparseDrive#66]
您好，我在模型训练阶段发现电脑的内存趋于稳定，但是在模型验证阶段，内存会异常增大，甚至导致out of memory，我疑惑您是否遇到过类似的问题？

**Comment by swc-17** [comment]
您好，好像没有遇到过类似的问题。

**Comment by YoushaaMurhij** [comment]
@guoyage, @swc-17, I have exactly the same problem. Any suggestions?
Thanks
