### ISSUE TITLE
Question about: num_temp_instances for map

### ISSUE THREAD

**Issue by julien-seitz** [swc-17/SparseDrive#68]
Hi,
is there a reason why num_temp_instances is set to 0 or -1 in stage 1 training for map only (not for BBoxes).
https://github.com/swc-17/SparseDrive/blob/main/projects/configs/sparsedrive_small_stage1.py#L277

In stage 2 it is set to 600 or -1
https://github.com/swc-17/SparseDrive/blob/main/projects/configs/sparsedrive_small_stage2.py#L132

And do you know the difference between setting this value to 0 or -1?
Thanks much

**Comment by swc-17** [comment]
For question 1, refer to [issue](https://github.com/swc-17/SparseDrive/issues/9).
For question 2, I think there is no difference.

**Comment by julien-seitz** [comment]
thanks much. The reference to StreamMapNet was helpful.
