### ISSUE TITLE
训练模块数据维度问题

### ISSUE THREAD

**Issue by gzspkgypt** [swc-17/SparseDrive#69]
您好，我将配置文件中with_motion_plan=True（规划模块变成True运行时），train 和 test代码分别报错维度问题，请问如何解决？
train的报错信息：
  File "SparseDrive-main/projects/mmdet3d_plugin/models/motion/motion_blocks.py", line 82, in forward
    plan_reg = self.plan_reg_branch(plan_query).reshape(bs, 1, 3 * self.ego_fut_mode, self.ego_fut_ts, 2)
RuntimeError: shape '[8, 1, 18, 6, 2]' is invalid for input of size 1152
test的报错信息：
  File "SparseDrive-main/projects/mmdet3d_plugin/models/motion/motion_blocks.py", line 82, in forward
    plan_reg = self.plan_reg_branch(plan_query).reshape(bs, 1, 3 * self.ego_fut_mode, self.ego_fut_ts, 2)
RuntimeError: shape '[1, 1, 18, 6, 2]' is invalid for input of size 144

**Comment by swc-17** [comment]
是用的stage1的config吗？ 可以直接使用stage2的。

**Comment by gzspkgypt** [comment]
感谢您的回复，我用的是stage1的config，我先尝试使用一下stage2。

**Comment by gzspkgypt** [comment]
您好，我使用了stage2的config，但还是维度还是不对，我也和git上的代码比较了，代码都是一样的。
![1](https://github.com/user-attachments/assets/ff5cd425-efdb-4c64-9634-1e85d8894aee)
![2](https://github.com/user-attachments/assets/f4d1887e-fa48-4438-aac6-eeaa6004aaba)
    plan_reg = self.plan_reg_branch(plan_query).reshape(bs, 1, 3 * self.ego_fut_mode, self.ego_fut_ts, 2)
RuntimeError: shape '[6, 1, 18, 6, 2]' is invalid for input of size 864

**Comment by swc-17** [comment]
可以检查下聚类出的anchor形状。

**Comment by gzspkgypt** [comment]
我检查了anchor形状
![4](https://github.com/user-attachments/assets/799f8eaf-efa0-4f2f-81fd-7f3e5df1187a)
![5](https://github.com/user-attachments/assets/4ff5090b-87c2-4ace-a868-b87e894e36eb)
聚类中k=6没有修改过

**Comment by gzspkgypt** [comment]
我检查了anchor形状
![4](https://github.com/user-attachments/assets/8da58391-f7eb-465e-8a04-51fc62d2509e)
![5](https://github.com/user-attachments/assets/b85ae04d-2581-4dcc-b259-205a1880f2ca)

**Comment by swc-17** [comment]
plan_query的shape应该是（6，1，18，256），18=3个command*6个mode.

**Comment by Bronyaer** [comment]
你好，我想知道，你是怎么修改的

**Comment by gzspkgypt** [comment]
你好，是聚类的维度问题，更改聚类文件中的配置就可以解决。

**Comment by Bronyaer** [comment]
不好意思，我是初学者，对于您说的修改聚类文件我其实听不太懂，我不太清楚是哪里的文件需要修改，可否更详细一点
