### ISSUE TITLE
Question about the `T_temp2cur` in instance_bank.py

### ISSUE THREAD

**Issue by jiangjudging** [swc-17/SparseDrive#7]
In lines 100-108:
```python
 T_temp2cur = self.cached_anchor.new_tensor(
                    np.stack(
                        [
                            x["T_global_inv"]
                            @ self.metas["img_metas"][i]["T_global"]
                            for i, x in enumerate(metas["img_metas"])
                        ]
                    )
                )
```
The result of `x["T_global_inv"] @ self.metas["img_metas"][i]["T_global"]` should always be identity matrix, which is not the expected result.

**Comment by swc-17** [comment]
```x["T_global_inv"]``` is from current frame while ```self.metas["img_metas"][i]["T_global"]``` is from previous frame.

**Comment by jiangjudging** [comment]
> `x["T_global_inv"]` is from current frame while `self.metas["img_metas"][i]["T_global"]` is from previous frame.

I see. I have ignored the `self` in `self.metas["img_metas"][i]["T_global"]`. 
Thanks for your reply.
