### ISSUE TITLE
关于Ego Status from T-1输入的问题

### ISSUE THREAD

**Issue by guoyage** [swc-17/SparseDrive#70]
![image](https://github.com/user-attachments/assets/7ca8ca9e-5095-4966-ba4e-74991efa4134)
我在代码中找到了规划模块的输入Front Feature Map和Symmetric Sparse Perception所在的位置，但是并没有看到Ego Status from T-1输入的代码。您能帮我指出这部分代码的位置吗？谢谢

**Comment by swc-17** [comment]
[here](https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/models/motion/instance_queue.py#L181).

**Comment by guoyage** [comment]
> [here](https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/models/motion/instance_queue.py#L181).

感谢您的回复，那么我产生了一个疑问，根据VAD的论文所述，其有两种结果，一种是采用Ego Status，另一种是不采用Ego Status作为输入，如下图所示
![image](https://github.com/user-attachments/assets/82c372d9-48d7-4b6a-911f-ca01b105186d)
dan'shi但是我看到您的论文里采用的对比结果是VAD不采用Ego Status时的结果，我很好奇，为了公平对比，这里是否应该取VAD的另一组结果进行对比？我不知道我这样的理解是否正确。期待您的回复

**Comment by swc-17** [comment]
我们模型里使用ego status是通过模型预测出来的,而不是直接用gt ego status.

**Comment by guoyage** [comment]
> 我们使用的ego status是通过模型预测出来的,而不是直接用gt ego status.

好的，感谢

**Comment by suayu** [comment]
也就是说，尽管在训练时候用到了LIDAR和CAN BUG的gt ego status作为真值，但是在推理的时候只使用了6环视相机图像？
