### ISSUE TITLE
About coordinate

### ISSUE THREAD

**Issue by Zbozhou** [swc-17/SparseDrive#71]
Thank you for your excellent work.
The LiDAR coordinate system differs between `mmdet3d v0.17.1` and `mmdet3d >= v1.x`, as shown below. Could you clarify which coordinate system you are following? Thank you.
![image](https://github.com/user-attachments/assets/ddaa8075-3450-4573-9920-ccafb274db64)

**Comment by Zbozhou** [comment]
Thank you for your quick response!

**Comment by YoushaaMurhij** [comment]
@swc-17,  @Zbozhou,  Nuscenes implements the first system above. Do I need to modify some parameters to implement the second system for inference?
