### ISSUE TITLE
question with eval_mode

### ISSUE THREAD

**Issue by hotdogcheesethu** [swc-17/SparseDrive#72]
感谢您的优秀工作！请问eval_mode中将所有的进程关闭对stage1训练有影响吗？因为eval_mode中with map经常卡死，超时，因此把他关闭了，请问作者是怎么解决这个问题的呢？感谢指导！

**Comment by swc-17** [comment]
对训练没有影响,全都关掉不会在训练过程中进行评测.

**Comment by hotdogcheesethu** [comment]
感谢您的回复！现在可以正常运行了
